name: New changeset
on: [push, pull_request]

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os: [macos-latest]
        node: [10, 12, 14, 15, 16]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: bash checknetwork.sh
      - run: node_modules/.bin/yarn install
      - run: node_modules/.bin/yarn build
      - run: node_modules/.bin/yarn test
      - post: test -e yarn-error.log && cat yarn-error.log
